### ISSUE TITLE
Helix readbacks

### ISSUE THREAD

**Issue by cmmercer** [MNGRLPychron/pychron#1]
**Describe the bug**
Tried viewing the readout for the Helix.

**To Reproduce**
1. Enabled HelixSpectrometer in initialization.xml
2. Launched pyvalve in simulation mode (USB to extraction line disconnected)
3. Went to menu: Spectrometer > View Readout
4. See error trace

Traceback (most recent call last):
  File "/Users/gs698mngrl/anaconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 163, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/gs698mngrl/anaconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/gs698mngrl/Documents/Pychron/Dev/pychron/pychron/spectrometer/tasks/spectrometer_actions.py", line 102, in perform
    v = new_readout_view(rv)
  File "/Users/gs698mngrl/Documents/Pychron/Dev/pychron/pychron/spectrometer/readout_view.py", line 352, in new_readout_view
    rv.start()
  File "/Users/gs698mngrl/Documents/Pychron/Dev/pychron/pychron/spectrometer/readout_view.py", line 246, in start
    self._refresh_loop()
  File "/Users/gs698mngrl/Documents/Pychron/Dev/pychron/pychron/spectrometer/readout_view.py", line 252, in _refresh_loop
    self._refresh()
  File "/Users/gs698mngrl/Documents/Pychron/Dev/pychron/pychron/spectrometer/readout_view.py", line 296, in _refresh
    args = r.config_compare()
  File "/Users/gs698mngrl/Documents/Pychron/Dev/pychron/pychron/spectrometer/readout_view.py", line 125, in config_compare
    if abs(self.value - self.config_value) > self.tolerance:
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

**Comment by cmmercer** [comment]
Readouts working.
